# Generated by Django 3.2.25 on 2024-08-04 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_auto_20240804_2151'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
