# Generated by Django 3.2.25 on 2024-08-04 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_wishitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishitem',
            name='quantity',
            field=models.SmallIntegerField(default=1),
        ),
    ]
