# Generated by Django 3.2.25 on 2024-08-05 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_wishitem_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishItem',
        ),
    ]
